//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastIndia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationDistance> LocationDistances { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<RouteHop> RouteHops { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
    }
}
