//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EastIndia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.RouteHops = new HashSet<RouteHop>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PriceID { get; set; }
        public Nullable<bool> Fragile { get; set; }
        public Nullable<bool> Refrigerated { get; set; }
        public Nullable<bool> RecordedDelivery { get; set; }
        public Nullable<bool> Weapon { get; set; }
        public Nullable<bool> LiveAnimal { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual Price Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteHop> RouteHops { get; set; }
    }
}
